universal7880: Drop duplicate sysprop assignments
Those are already being defined elsewhere.

error: found duplicate sysprop assignments:
dalvik.vm.isa.arm.variant=cortex-a15
dalvik.vm.isa.arm.variant=cortex-a53
error: found duplicate sysprop assignments:
dalvik.vm.isa.arm64.variant=generic
dalvik.vm.isa.arm64.variant=cortex-a53

Change-Id: I57e7bbe2bd733756f22590bf72b087d5f35ce265